language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - COMPOSER_FLAGS=""
  - COMPOSER_FLAGS="--prefer-lowest"

matrix:
  allow_failures:
    - php: 7.3
      env: COMPOSER_FLAGS="--prefer-lowest"

install:
  - travis_retry composer update --no-interaction --no-suggest --prefer-dist --prefer-stable $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit