language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

sudo: false

install: travis_retry composer update --no-interaction --no-suggest --prefer-dist --prefer-stable $PREFER_LOWEST

script: vendor/bin/phpunit